### PR TITLE
Auth0 authentication using Auth0 Rule

### PR DESCRIPTION
**Pull request by kbrandwijk**
This authentication examples uses Auth0, and retrieves the Graphcool token as part of the Auth0 authentication process using Auth0 Rules. The Graphcool token is added as claim to the payload of the id_token received from Auth0.
This example does not require any Schema Extensions on the Graphcool side! Also, no Auth0 token exchange is needed between Auth0 and Graphcool.
Everything happens in one step, regardless of the Auth0 authentication method (Auth0 lock, auth0-react-native, Auth0.js, endpoint calls).

### CODE REVIEW

**Comment by kaumac** [comment]
@kbrandwijk I haven't used Auth0 a lot, so I don't know a lot about it, but would it be possible to use this without Auth0 Lock?

**Comment by kbrandwijk** [comment]
@kaumac Yes, any Auth0 authentication can be used without Auth0 lock. That's completely optional. You can also use the Auth0 javascript library (https://auth0.com/docs/libraries/auth0js/v8), or call the endpoints yourself.

The only thing this PR does, is put the Graphcool token in the Auth0 token. This happens completely independent on which method you use to authorize with Auth0.

**Comment by marktani** [comment]
I'd prefer to see a custom mutation instead of using the Auth0 auth provider, as we're currently transitioning away from that.

**Comment by Geczy** [comment]
Does it allow OIDC conformant clients?

**Comment by kbrandwijk** [comment]
@Geczy Yes, this fully supports the OIDC conformant authentication flow.

**Comment by Geczy** [comment]
Auth0 doesn't allow saving the rule due to errors

```
The script has errors. Do you want to save it anyway?

Line 2: Unexpected '`'.
Line 3: Missing semicolon.
Line 3: 'projectId' is not defined.
Line 3: Expected an identifier and instead saw 'var'.
Line 9: Unexpected '`'.
Line 12: Unexpected '`'.
Line 13: Expected ')' and instead saw 'JSON'.
Line 13: 'body' is not defined.
Line 13: Expected '}' to match '{' from line 12 and instead saw ':'.
Line 14: Expected an assignment or function call and instead saw an expression.
Line 14: Missing semicolon.
Line 14: Expected '}' to match '{' from line 14 and instead saw ':'.
Line 14: Expected an assignment or function call and instead saw an expression.
Line 14: Missing semicolon.
Line 14: Expected '(end)' and instead saw '}'.
Line 14: Missing semicolon.
Line 14: Expected '}' to match '{' from line 1 and instead saw ':'.
```

**Comment by kbrandwijk** [comment]
Yes, the built-in code validator at Auth0 is a bit moody. You can save anyways.

**Comment by Geczy** [comment]
Auth0 also complains about enabling the Password grant 
```
Using Password or MFA grant types with public clients is not recommended. 
To use the Client Credentials grant you have to set a Token Endpoint Auth Method other than "none". 
See our documentation for more information.```

I'm doing this on my auth0js SPA client. I'm afraid unchecking refresh token etc will disable silent reauthentication

![image](https://user-images.githubusercontent.com/1036968/30874604-d994691a-a2be-11e7-896c-02a9c8f5eb46.png)

**Comment by Geczy** [comment]
The rule failed for me

```js
{
  error: "access_denied", 
  errorDescription: "Cannot read property 'token' of null", 
  state: "n2-pDoV0QY2nv4LFQdApcl-H8NhsbPrZ"
}

```
```
1:35:17 PM: new webtask request 1506447317845.783794
1:35:18 PM: finished webtask request 1506447317845.783794 with HTTP 500 in 761ms
1:35:18 PM: setting tenant quarantine
1:35:18 PM: faulting webtask container following request 1506447317845.783794 failure
```

**Comment by Geczy** [comment]
```
1:44:46 PM: new webtask request 1506447886194.77670
1:44:46 PM: null
1:44:46 PM: null
1:44:46 PM: {
  "code": 500,
  "error": "Script generated an unhandled asynchronous exception.",
  "details": "TypeError: Cannot read property 'token' of null",
  "name": "TypeError",
  "message": "Cannot read property 'token' of null",
  "stack": "TypeError: Cannot read property 'token' of null\n    at Request._callback (/data/io/30d1bf1516624bf8923d265223a8501e/webtask.js:100:51)\n    at Request.self.callback (/data/sandbox/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:87:13)\n    at Request.emit (events.js:172:7)\n    at Request.<anonymous> (/data/sandbox/node_modules/request/request.js:1163:10)\n    at emitOne (events.js:77:13)\n    at Request.emit (events.js:169:7)\n    at IncomingMessage.<anonymous> (/data/sandbox/node_modules/request/request.js:1085:12)\n    at IncomingMessage.g (events.js:260:16)\n    at emitNone (events.js:72:20)\n    at IncomingMessage.emit (events.js:166:7)\n    at endReadableNT (_stream_readable.js:923:12)\n    at nextTickCallbackWith2Args (node.js:511:9)\n    at process._tickDomainCallback (node.js:466:17)"
}
1:44:46 PM: Code generated an uncaught exception:  TypeError: Cannot read property 'token' of null
    at Request._callback (/data/io/30d1bf1516624bf8923d265743a8504e/webtask.js:100:51)
    at Request.self.callback (/data/sandbox/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/data/sandbox/node_modules/request/request.js:1163:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/data/sandbox/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickDomainCallback (node.js:466:17)
1:44:46 PM: finished webtask request 1506447886194.77670 with HTTP 500 in 767ms
1:44:46 PM: setting tenant quarantine
1:44:46 PM: faulting webtask container following request 1506447886194.77670 failure
```

**Comment by Geczy** [comment]
Oh your rule is adding the periods, and I was including the periods. So there were double periods in my PAT. Now it's working

**Comment by kbrandwijk** [comment]
Yeah, sorry about that. It's a bit of an ugly workaround for the max. metadata length restriction, I hope Graphcool will come up with a shorter version of a 'client secret' than the current token, it's on my wishlist...

**Comment by kbrandwijk** [comment]
@marktani Any plans to include this example?

**Comment by Geczy** [comment]
This example is a must have since Graph.cool is still using legacy auth0 integration, which will be deprecated soon

**Comment by marktani** [comment]
I like this example, but it does not fit into the new `templates` concept. It probably better suits a FAQ article than this repo. I'll think about it! 🙂

**Comment by kbrandwijk** [comment]
@marktani I agree, do not merge. I will release a solution for this shortly. I'll leave this one open until it's ready.

**Comment by patrick-samy** [comment]
I have setup the rule and still getting the same error while debugging:

"The provided idToken is invalid. Please see https://auth0.com/docs/tokens/id_token for how to obtain a valid idToken"

I'm not sure I understand how this helps Graphcool APIs use a RS256 token, which seems to be the main issue here.

Any ideas?

**Comment by patrick-samy** [comment]
My bad, one more thing to do for this to work: disable the legacy Auth0 integration.

**Comment by patrick-samy** [comment]
Is the rule code taking care of verifying the Auth0 token?

**Comment by kbrandwijk** [comment]
It doesn't have to, as it's executed internally as part of the login process. The token never leaves Auth0 before the rule executes.

**Comment by michaelpumo** [comment]
Will all this work with an SPA set in Auth0?

Also, I would rather use auth0-js for my own custom login than the Auth0 Lock. Is that possible too? If so a guide on this distinction would be very welcome!

Thanks.

**Comment by huan** [comment]
Authentication via Auth0 Rule is a better idea for me and I'd like to use this method instead of using the official Graphcool auth0 template because it's more simple for my code.

Also, I'd like to suggest Graphcool provide a method that uses Auth0 JWT directly, so we can make the auth process more simple.

**Comment by digitaltopo** [comment]
Having similar issues as others in this thread. Is there a clear tutorial or example we can reference for implementing Auth0 integration?

I've got a React + Apollo app, using Auth0.js and seeing:
```
Error: GraphQL error: The provided idToken is invalid. Please see https://auth0.com/docs/tokens/id_token for how to obtain a valid idToken
```

I was following this tutorial: https://codeburst.io/using-auth0-with-graphcool-part-2-c44c1fef0740

Thanks for your help

**Pull request closed without merging**
