### PR TITLE
Fix links to docs

### PR DESCRIPTION
**Pull request by denkristoffer**

### CODE REVIEW

**Comment by marktani** [comment]
Could you actually adjust the PR to link to https://www.graph.cool/docs/reference/service-definition/templates-zeiv8phail & anchors accordingly? 🙂

**Comment by denkristoffer** [comment]
By the way, I just noticed that it seems like the anchor links don't work. The page scrolls to the top after page loads.

**Comment by kbrandwijk** [comment]
@denkristoffer I think that should be a new issue in the main repo.

**Comment by marktani** [comment]
Thanks! 🎉 And agreed with @kbrandwijk 🙂

**Pull request merged**
